name = "two_way_automata"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["TwoWayAutomata", "KozenExample", "NonTermExample",  "KthLastExample"]
lintDriver = "batteries/runLinter"

# precompileModules = true

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "TwoWayAutomata"

[[lean_exe]]
name = "KozenExample"
root = "TwoWayAutomata.KozenExample"
needs = ["TwoWayAutomata"]

[[lean_exe]]
name = "NonTermExample"
root = "TwoWayAutomata.NonTermExample"
needs = ["TwoWayAutomata"]

[[lean_exe]]
name = "KthLastExample"
root = "TwoWayAutomata.KthLastExample"
needs = ["TwoWayAutomata"]
